// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Models.Database.Context;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230612152559_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web.Models.Database.FavoriteFoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("FoodId")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("FavoriteFoods");
                });

            modelBuilder.Entity("Web.Models.Database.FoodMaterials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("FoodId")
                        .HasColumnOrder(1);

                    b.Property<string>("MaterialCount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaterialCount")
                        .HasColumnOrder(3);

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialId")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FoodMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6643),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "3",
                            MaterialId = 20,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6643)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6646),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "2",
                            MaterialId = 21,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6646)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6647),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "1",
                            MaterialId = 2,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6648)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6648),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "1",
                            MaterialId = 22,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6649)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6649),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "2",
                            MaterialId = 14,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6649)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6650),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "1",
                            MaterialId = 24,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6650)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6651),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "2",
                            MaterialId = 25,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6651)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6653),
                            Creator = 1,
                            FoodId = 1,
                            MaterialCount = "8",
                            MaterialId = 26,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6653)
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6654),
                            Creator = 1,
                            FoodId = 2,
                            MaterialCount = "8",
                            MaterialId = 15,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6654)
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6655),
                            Creator = 1,
                            FoodId = 2,
                            MaterialCount = "1",
                            MaterialId = 2,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6655)
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6656),
                            Creator = 1,
                            FoodId = 2,
                            MaterialCount = "4",
                            MaterialId = 14,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6656)
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6656),
                            Creator = 1,
                            FoodId = 2,
                            MaterialCount = "3",
                            MaterialId = 16,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6657)
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6657),
                            Creator = 1,
                            FoodId = 2,
                            MaterialCount = "1",
                            MaterialId = 18,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6658)
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6658),
                            Creator = 1,
                            FoodId = 2,
                            MaterialCount = "3",
                            MaterialId = 13,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6659)
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6659),
                            Creator = 1,
                            FoodId = 3,
                            MaterialCount = "1/2paket",
                            MaterialId = 28,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6660)
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6660),
                            Creator = 1,
                            FoodId = 3,
                            MaterialCount = "1 tatlı kaşığı",
                            MaterialId = 21,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6661)
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6661),
                            Creator = 1,
                            FoodId = 3,
                            MaterialCount = "1 paket",
                            MaterialId = 19,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6662)
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6662),
                            Creator = 1,
                            FoodId = 3,
                            MaterialCount = "1/2 çay kaşığı",
                            MaterialId = 6,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6662)
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6663),
                            Creator = 1,
                            FoodId = 3,
                            MaterialCount = "1 çay kaşığı",
                            MaterialId = 5,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6663)
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6664),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "2 su bardağı",
                            MaterialId = 30,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6664)
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6665),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "1 adet",
                            MaterialId = 2,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6665)
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6666),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "3 su bardağı",
                            MaterialId = 11,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6666)
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6667),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "2 yemek kaşığı",
                            MaterialId = 21,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6667)
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6667),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "1 yemek kaşığı",
                            MaterialId = 29,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6668)
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6668),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "1 çay kaşığı",
                            MaterialId = 12,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6669)
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6669),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "1 çay kaşığı",
                            MaterialId = 6,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6670)
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6670),
                            Creator = 1,
                            FoodId = 4,
                            MaterialCount = "1 çay kaşığı",
                            MaterialId = 5,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6670)
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6671),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "2 su bardağı",
                            MaterialId = 3,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6671)
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6672),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "2 yemek kaşığı",
                            MaterialId = 31,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6672)
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6673),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "2,5 su bardağı kaynar ",
                            MaterialId = 27,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6673)
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6674),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "2 yemek kaşığı ",
                            MaterialId = 21,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6674)
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6675),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "1 yemek kaşığı ",
                            MaterialId = 13,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6675)
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6676),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "1 tatlı kaşığı ",
                            MaterialId = 5,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6676)
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6676),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "3 damla ",
                            MaterialId = 17,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6677)
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6677),
                            Creator = 1,
                            FoodId = 5,
                            MaterialCount = "1/2 çay kaşığı ",
                            MaterialId = 32,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6678)
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6678),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "9 adet büyük boy ",
                            MaterialId = 33,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6679)
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6679),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "5 diş ",
                            MaterialId = 14,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6680)
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6680),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "5 yemek kaşığı ",
                            MaterialId = 20,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6681)
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6681),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "1 adet orta boy ",
                            MaterialId = 2,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6681)
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6683),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "5 su bardağı sıcak  ",
                            MaterialId = 27,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6683)
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6683),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "1 yemek kaşığı  ",
                            MaterialId = 24,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6684)
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6684),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "1 çay kaşığı  ",
                            MaterialId = 5,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6685)
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6685),
                            Creator = 1,
                            FoodId = 6,
                            MaterialCount = "1 çay kaşığı  ",
                            MaterialId = 6,
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6686)
                        });
                });

            modelBuilder.Entity("Web.Models.Database.Foods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<int>("FoodCookingTime")
                        .HasColumnType("int")
                        .HasColumnName("FoodCookingTime")
                        .HasColumnOrder(7);

                    b.Property<string>("FoodCookingTimeText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FoodCookingTimeText")
                        .HasColumnOrder(8);

                    b.Property<int>("FoodCountForPeople")
                        .HasColumnType("int")
                        .HasColumnName("FoodCountForPeople")
                        .HasColumnOrder(3);

                    b.Property<string>("FoodCountForPeopleText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FoodCountForPeopleText")
                        .HasColumnOrder(4);

                    b.Property<string>("FoodImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FoodImage")
                        .HasColumnOrder(2);

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FoodName")
                        .HasColumnOrder(1);

                    b.Property<int>("FoodPreparingTime")
                        .HasColumnType("int")
                        .HasColumnName("FoodPreparingTime")
                        .HasColumnOrder(5);

                    b.Property<string>("FoodPreparingTimeText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FoodPreparingTimeText")
                        .HasColumnOrder(6);

                    b.Property<string>("FoodRecipe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FoodRecipe")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6623),
                            Creator = 1,
                            FoodCookingTime = 30,
                            FoodCookingTimeText = "Dakika",
                            FoodCountForPeople = 4,
                            FoodCountForPeopleText = "Kişilik",
                            FoodImage = "/images/tavuklu-bulgur-pilavi-yemekcom-1.jpg",
                            FoodName = "Fırında Tavuklu Bulgur Kapama",
                            FoodPreparingTime = 15,
                            FoodPreparingTimeText = "Dakika",
                            FoodRecipe = "İlk olarak soğan, havuç, biber ve kabağı ufak küpler halinde doğrayıp ayrı ayrı kenarda bekletin.\r\n    Geniş bir tava ya da tencereye zeytinyağını, tereyağını koyup soğanları tencereye ekleyin ve orta ateşte hafif tuzlayarak yumuşayana kadar pişirin.\r\n    Tavaya sırasıyla havuçları, biberleri, bir diş doğranmış sarımsağı ve son olarak kabakları ekleyip soteleyin.\r\n    Tavaya tuzu ve baharatların ardından salçayı da ekleyin, 1 dakika kadar kavurduktan sonra bulgurları da ekleyip tüm malzeme bütünleşene kadar 3-4 dakika daha kavurun.\r\n    Karışımı fırın tepsisine aktarın, haşlanmış tavukları üzerine dizin, sıcak suyu da ekleyip üstünü folyoyla kaplayın.\r\n    Yemeği 200 derecelik sıcak fırında 20 dakika pişirdikten sonra folyoyu alın ve üzeri kızarana kadar 10 dakika daha pişirin. Servis edene kadar kapalı fırında demlenmeye bırakabilirsiniz. Afiyet olsun.",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6624)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6626),
                            Creator = 1,
                            FoodCookingTime = 20,
                            FoodCookingTimeText = "Dakika",
                            FoodCountForPeople = 4,
                            FoodCountForPeopleText = "Kişilik",
                            FoodImage = "/images/kori-soslu-tavuk-yemekcom.jpg",
                            FoodName = "Köri Soslu Tavuk",
                            FoodPreparingTime = 30,
                            FoodPreparingTimeText = "Dakika",
                            FoodRecipe = "Tavuk kalçalarını ufak lokmalık parçalar halinde kesin. Bir kasenin içinde tavukları, soğan rendesi, sarımsak, yoğurt, limon suyu, tuz, karabiber ve köri ile karıştırın. Kaseyi streçleyin ve buzdolabında 3 saat dinlendirin.\r\n    Geniş bir tavayı ısıtın ve tavukları önlü arkalı az yağda 3-4 dakika kızartın. Kızaran tavukların üstüne krema ve köriyi de ekleyip ateşin altını en kısık konuma getirin.\r\n\r\n    Sos koyulaşınca ocaktan alın ve yemeğin üstüne ince kıyılmış kişniş ya da maydanoz serperek servis edin. Afiyet olsun.",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6627)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6628),
                            Creator = 1,
                            FoodCookingTime = 15,
                            FoodCookingTimeText = "Dakika",
                            FoodCountForPeople = 2,
                            FoodCountForPeopleText = "Kişilik",
                            FoodImage = "/images/kremali-spagetti-sunum-yemekcom.webp",
                            FoodName = "Kremalı Spagetti",
                            FoodPreparingTime = 5,
                            FoodPreparingTimeText = "Dakika",
                            FoodRecipe = "Tencereye 2 litre kadar su ekleyin ve güzelce ısıtın. Üzerine spagettileri ekleyin. Haşlanana kadar 10-11 dakika civarı pişirin.\r\n\r\n    Kremayı ve tereyağını tencereye alın. Fokurdayana kadar güzelce pişirin.\r\n \r\n    Üzerine süzdüğünüz spagettileri ilave edin. Tuzunu ve karabiberini ekleyin.\r\n\r\n    Kıyılmış maydanoz ve cherry domatesle süsleyebilirsiniz. Afiyet olsun!\r\n ",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6628)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6629),
                            Creator = 1,
                            FoodCookingTime = 40,
                            FoodCookingTimeText = "Dakika",
                            FoodCountForPeople = 4,
                            FoodCountForPeopleText = "Kişilik",
                            FoodImage = "/images/sutlu-kurufasulye-yeni-onecikan.jpg",
                            FoodName = "Sütlü Kuru Fasulye",
                            FoodPreparingTime = 15,
                            FoodPreparingTimeText = "Dakika",
                            FoodRecipe = "Geceden ıslatmış olduğunuz fasulyelerin suyunu süzün ve tencereye alın. Süt ve suyu karıştırarak üzerini geçene kadar ekleyin ve kaynamaya bırakın.Biraz kaynadıktan sonra süzgeç yardımıyla süzün. Tencereye yağ ve küp küp doğranmış soğanları ekleyip kavurun. Soğanların rengi dönünce salça ve fasulyeleri ekleyerek kavurun. Hizasını geçene kadar su ekleyip baharatlarını ilave edin. Süt ile kaynatıldığı için pişme süresi yarı yarıya kısalıyor,kontrollü pişirmekte fayda var. Piştikten sonra biraz dinlendirin. Ardından servis edin. Afiyetler olsun!    ",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6630)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6631),
                            Creator = 1,
                            FoodCookingTime = 20,
                            FoodCookingTimeText = "Dakika",
                            FoodCountForPeople = 4,
                            FoodCountForPeopleText = "Kişilik",
                            FoodImage = "/images/tel-sehriyeli-pirinc-pilavi-onecikan.jpg",
                            FoodName = "Tel Şehriyeli Pirinç Pilav",
                            FoodPreparingTime = 10,
                            FoodPreparingTimeText = "Dakika",
                            FoodRecipe = "Pirincinizi iyice yıkadıktan sonra tuzlu sıcak suda yarım saat nişastasını atması için bekletin Şehriyeyi pilav tenceresine alarak tereyağı ve sıvı yağını ekleyip rengi dönene kadar kavurun. Pirinci ekleyin, bir miktar daha kavurun. Bu aşamada limon suyu ve şekeri ekleyip üzerine suyunu ekleyin. Tuzunu da ekleyip karıştırdıktan sonra kapağını kapatın, kısık ateşte pişmeye bırakın. Suyunu çeken pilavın üzerine bir bez kapatın ve kapağını kapatarak demlenmesi için bekleyin. Tel şehriyeli pirinç pilavı hazır, afiyetler olsun.",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6631)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6632),
                            Creator = 1,
                            FoodCookingTime = 30,
                            FoodCookingTimeText = "Dakika",
                            FoodCountForPeople = 4,
                            FoodCountForPeopleText = "Kişilik",
                            FoodImage = "/images/kozlenmis-domates-corbasi-one-cikan.webp",
                            FoodName = "Közlenmiş Domates Çorbası ",
                            FoodPreparingTime = 20,
                            FoodPreparingTimeText = "Dakika",
                            FoodRecipe = "Fırınınızı 180 derecede ısıtmaya başlayın.Domatesleri iyice yıkayın ve kabuklarını soymadan ortadan ikiye bölün.Fırın tepsinize yağlı kağıt serin ve ortadan ikiye kestiğiniz domatesleri dizin. Üzerine biraz zeytinyağı gezdirin. Önceden ısıtılmış fırında yaklaşık 30 dakika kadar pişirin. Sarımsakları domatesleri fırına attıktan 15 dakika sonra atın.Közlenen domates ve sarımsakları fırından alın. Kabuklarını soyun. Sarımsakları ezin. Soğanı minik küpler halinde doğrayın. Bir tencerenin içerisine alın. Üzerine zeytinyağı ve salçayı ilave edin.Soğanlar iyice kavrulana kadar pişirmeye devam edin. Pişince içerisine ezdiğiniz sarımsakları ekleyin. Birkaç kez daha çevirin. Ardından közlenmiş domatesleri ve sıcak suyu ekleyin. Domatesler iyice eriyene kadar pişirin. Orta ateşte domatesler iyice eriyene kadar pişirin. Tuz ve baharatlarını ilave edin. Kıvam almaya başladığında ocaktan alın ve karışımı blenderdan geçirin. Üzerini dilediğiniz gibi süsleyerek sıcak sıcak servis edin. Afiyet olsun.",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6632)
                        });
                });

            modelBuilder.Entity("Web.Models.Database.Materials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<string>("MaterialImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaterialImage")
                        .HasColumnOrder(2);

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaterialName")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6537),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Dana Kıyma",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6538)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6539),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Soğan",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6540)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6541),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Pirinç",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6541)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6541),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Maydanoz",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6542)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6542),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Tuz",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6543)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6543),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Karabiber",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6544)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6545),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Pul biber",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6545)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6546),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Yumurta",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6546)
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6547),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Un",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6548)
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6549),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Galeta Unu",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6549)
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6550),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Süt",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6551)
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6551),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Kimyon",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6551)
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6552),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Sıvı Yağ",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6552)
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6553),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Sarımsak",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6553)
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6554),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Tavuk Kalça",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6555)
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6555),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Yoğurt",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6556)
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6556),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Limon Suyu",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6556)
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6557),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Köri",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6557)
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6558),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Krema",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6558)
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6559),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Zeytinyağı",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6559)
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6591),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Tereyağı",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6591)
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6592),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Havuç",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6593)
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6593),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Kabak",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6594)
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6594),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Domates Salçası",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6595)
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6595),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Pilavlık Bulgur",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6596)
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6596),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Tavuk Baget",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6596)
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6597),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Su",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6597)
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6599),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Spagetti",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6599)
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6600),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Biber Salçası",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6600)
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6601),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Kuru Fasulye",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6601)
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6601),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Tel Şehriye",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6602)
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6602),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Toz Şeker",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6603)
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6603),
                            Creator = 1,
                            MaterialImage = "",
                            MaterialName = "Domates",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6604)
                        });
                });

            modelBuilder.Entity("Web.Models.Database.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email")
                        .HasColumnOrder(3);

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Firstname")
                        .HasColumnOrder(1);

                    b.Property<int?>("ForgotPassword")
                        .HasColumnType("int")
                        .HasColumnName("ForgotPassword")
                        .HasColumnOrder(6);

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lastname")
                        .HasColumnOrder(2);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password")
                        .HasColumnOrder(4);

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProfileImage")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6445),
                            Creator = 1,
                            Email = "admin@admin.com",
                            Firstname = "Admin",
                            Lastname = "",
                            Password = "123456",
                            ProfileImage = "chefimage.png",
                            UpdateDate = new DateTime(2023, 6, 12, 18, 25, 59, 506, DateTimeKind.Local).AddTicks(6453)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
